### ISSUE TITLE
Unclear NGINX_CONTAINER

### ISSUE THREAD

**Issue by budarin** [mikew/docker-gen-letsencrypt#2]
Hi!

I have some questions:
- what does it mean `docker-gen-letsencrypt_nginx_1` ? 
- why not `NGINX_CONTAINER=nginx` ?
- what if we have some nginx instances?

thanks

**Comment by mikew** [comment]
> what does it mean docker-gen-letsencrypt_nginx_1

That's the name docker-compose will give the nginx container, by default. It combines the directory name and the name of the service. So, assuming you start with a `docker-compose.yml` file in a directory named `docker-gen-letsencrypt` which contains a service named `nginx`, the container you'd want to restart would in fact be `docker-gen-letsencrypt_nginx_1`

> why not NGINX_CONTAINER=nginx

Because the suggestion is just to use docker-compose. You can name things whatever you'd like :)

> what if we have some nginx instances

Do you mean what if you have multiple nginx instances you need to restart? Typically there's just one reverse proxy that needs to reload when new certificates are generated, that's the only workflow this supports at the moment. You can mount your own file at `/app/reload-nginx`, that script will be called when a reload is needed.

**Comment by budarin** [comment]
Thanks for response!

I use to Docker Swarm. It uses service discovery and round robin algorithm for load balancing so we can have some proxy instances for better load balancing between proxy instances.

It seems to me that the best option would be to specify the name of the stack/compose and the service name. Then in the script, you could use template to get all the instances and notify them a command to restart

Thanks

**Comment by mikew** [comment]
> It seems to me that the best option would be to specify the name of the stack/compose and the service name

I wouldn't want to only have a solution that requires docker-compose/swarm, but happy to add it in addition to a simple container name. Is there anything preventing you from using this image as a base and placing your own script at `/app/reload-nginx`? I have no experience with swarm, so I would be flying blind there.

When it comes to compose, I do know that newer versions of docker-compose do pretty good labelling, so there's probably a way I can get started on supporting some variables like `DOCKER_COMPOSE_PROJECT` and `DOCKER_COMPOSE_SERVICE`

**Comment by budarin** [comment]
the idea: some guys use labels to find and reload containers

https://hub.docker.com/r/helder/docker-gen/

**Comment by mikew** [comment]
Oh that's neat, I'll borrow the idea and add support for multiple filters, something like `DOCKER_LABELS=label1=value,label2=value`. Will that work for your use case?
